sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - clang
      - clang++
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev
      - libunwind8-dev

env:
  - CC=/usr/bin/clang CXX=/usr/bin/clang++

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.2/bazel-0.1.2-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.2-installer-linux-x86_64.sh
  - ./bazel-0.1.2-installer-linux-x86_64.sh --user

script: 
  - which clang
  - clang --version
  - which clang++
  - clang++ --version 
  - ./bazel_configure.py
  - bazel --bazelrc=tools/travis-ci/bazel.rc test heron/...
