sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev
      - libunwind8-dev

env:
  - CC=clang CXX=clang++

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.2/bazel-0.1.2-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.2-installer-linux-x86_64.sh
  - ./bazel-0.1.2-installer-linux-x86_64.sh --user

script: 
  - which clang
  - clang --version
  - which clang++
  - clang++ --version 
  - clang  -E -x c++ - -v 2>&1 < /dev/null
  - which gcc-4.8
  - gcc --version
  - which g++-4.8
  - g++ --version 
  - ./bazel_configure.py
  - bazel --bazelrc=tools/travis-ci/bazel.rc test --compiler=clang heron/...
