sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev

env:
  - CC=gcc-48 CXX=g++-4.8

before_install:
  - which gcc
  - gcc --version
  - which gcc-4.8
  - gcc-4.8 --version
  - wget http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
  - tar xvfz libunwind-1.1.tar.gz
  - cd libunwind-1.1 && ./configure && make install
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.2/bazel-0.1.2-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.2-installer-linux-x86_64.sh
  - ./bazel-0.1.2-installer-linux-x86_64.sh --user

script: 
  - which gcc-4.8
  - gcc --version
  - which g++-4.8
  - g++ --version 
  - ./bazel_configure.py
  - bazel --bazelrc=tools/travis-ci/bazel.rc test --compiler=clang heron/...
