language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev
      - libunwind-dev

env:
  - CC=/usr/bin/gcc-4.8 CXX=/usr/bin/g++-4.8

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 g++-4.8 -f -y
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.2/bazel-0.1.2-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.2-installer-linux-x86_64.sh
  - ./bazel-0.1.2-installer-linux-x86_64.sh --user

script: 
  - which gcc
  - gcc --version
  - which gcc-4.8
  - gcc-4.8 --version 
  - ./bazel_configure.py
  - bazel --bazelrc=tools/travis-ci/bazel.rc test heron/...
