# scheduler class for distributing the topology for execution
heron.scheduler.class:            com.twitter.heron.scheduler.local.LocalScheduler

# packing algorithm for packing instances into containers
heron.packing.algorithm.class:    com.twitter.heron.packing.roundrobin.RoundRobinPacking

# uploader class for transferring the topology jar/tar files to storage
heron.uploader.class:             com.twitter.heron.uploader.localfs.LocalFileSystemUploader

# state manager class for managing state in a persistent fashion
heron.state.manager.class:        com.twitter.heron.statemgr.localfs.LocalFileSystemStateManager
