# scheduler class for distributing the topology for execution
heron.class.scheduler:                       com.twitter.heron.spi.scheduler.NullScheduler

# launcher class for submitting and launching the topology
heron.class.launcher:                        com.twitter.heron.scheduler.aurora.AuroraLauncher

# runtime class for managing topology
heron.class.runtime.manager:                 com.twitter.heron.scheduler.aurora.AuroraRuntimeManager

# working directory for the topologies
heron.scheduler.local.working.directory:     ${HOME}/.herondata/topologies/${CLUSTER}/${ROLE}/${TOPOLOGY}

# location of java - pick it up from shell environment
heron.directory.sandbox.java.home:           /usr/lib/jvm/java-1.8.0-openjdk-amd64/
