# uploader class for transferring the topology jar/tar files to storage
heron.class.uploader:                            com.twitter.heron.uploader.localfs.LocalFileSystemUploader

# name of the directory to upload topologies for local file system uploader
heron.uploader.localfs.file.system.directory:    /vagrant/.herondata/repository/topologies/${CLUSTER}/${ROLE}/${TOPOLOGY}

# URI of heron core release package
heron.core.release.package.uri:                  "file:///vagrant/.herondata/dist/heron-core-release.tar.gz"